name: 'Deploy to AWS S3'
description: 'Deploy the website to an S3 bucket'
inputs:
  bucket-name:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-2'
  dist-folder:
    description: 'The directory to deploy to the S3 bucket'
    required: true
runs:
  using: 'node16'
  main: 'main.js'